rootUrl = 'https://nix.ladas552.me'
language = 'en-US'
title = 'Nix'
author = 'ladas552'

# Code blocks highlighting
[highlighter]
enable = false
# engine = 'prism' # Can be 'prism' or 'hljs'. Defaults to 'prism'

# RSS feed
[rss]
enable = true
description = 'Latest posts'
ttl = 60
image = '/assets/favicon.png'

# Extras
[extra]
license = "GPLv3"
favicon_path = '/assets/favicon.png'
footer_author_link = "https://codeberg.org/amartin"
enable_mermaid = true

[extra.nav]
About = '/about'
Posts = '/posts'
Tags = '/categories'
RSS = '/rss.xml'

[extra.footer]
GitHub = 'https://github.com/NTBBloodbath'
Codeberg = 'https://codeberg.org/amartin'
