# helium
[helium]
src.github_tag = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64.AppImage"

[helium-wrapped]
src.git = "https://github.com/Michael-C-Buckley/nixos"
fetch.github = "Michael-C-Buckley/nixos"

[jail-nix]
src.git = "https://git.sr.ht/~alexdavid/jail.nix"
fetch.git = "https://git.sr.ht/~alexdavid/jail.nix"

# neorg
[neorg-interim-ls]
src.git = "https://github.com/benlubas/neorg-interim-ls"
fetch.github = "benlubas/neorg-interim-ls"

[neorg-conceal-wrap]
src.git = "https://github.com/benlubas/neorg-conceal-wrap"
fetch.github = "benlubas/neorg-conceal-wrap"

[neorg-query]
src.git = "https://github.com/benlubas/neorg-query"
fetch.github = "benlubas/neorg-query"

# neovim plugins
[heirline-components]
src.git = "https://github.com/Zeioth/heirline-components.nvim"
fetch.github = "Zeioth/heirline-components.nvim"

[cyrillic]
src.git = "https://github.com/nativerv/cyrillic.nvim"
fetch.github = "nativerv/cyrillic.nvim"
